[package]
name = "starkwaves-client"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "2.1.0", default-features = false, features = ["display"] }
thiserror = "2.0.17"
rand = "0.8.5"
starknet = "0.17.0"
cairo-native = "0.8.0"
cairo-lang-sierra = "2.14.0"
serde_json = "1.0"

[build-dependencies]
cairo-native = "0.8.0"
cairo-lang-sierra = "2.14.0"
serde_json = "1.0"