[workspace]
resolver = "2"
members = ["client", "tui"]

[patch.crates-io]
starknet-rust-core = { path = "patches/starknet-rust-core" }
cainome-cairo-serde = { path = "patches/cainome-cairo-serde" }

[workspace.dependencies]
enum-as-inner = "0.6.1"
async-trait = "0.1.89"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "rt", "time", "process", "fs", "io-util"] }
log = "0.4.29"
starknet-rust = "0.19.0"
starknet-rust-core = "0.19.0"
starknet-rust-tokio-tungstenite = "0.19.0"
dirs = "6.0.0"
dotenv = "0.15.0"
url = { version = "2", features = ["serde"] }
thiserror = "2.0.17"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"